import Head from 'next/head'
import PostCard from "../components/PostCard"

const posts = [
  { title: "intro to react js", excerpts: "react js is created by facebook comunity" },
  { title: "new features in new version of next js", excerpts: "next js is created by ajjwgl fwhwg ..." }
]

export default function Home() {
  return (
    <>
      <Head>
        <title>mosdev blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto py-4 px-10 mb-8">
        <div className="grid grid-cols-1 md:grid-cols-12 gap-10">
          <div className="col-span-1 md:col-span-8">
            <h1 className='text-center text-3xl capitalize' >blog articles</h1>
            {
              posts.map((post, index) => (
                <div key={index} className="container">
                   < PostCard post={post} />
                </div>
              ))
            }
          </div>
          <div className="col-span-1 md:col-span-4">
            <div className="md:sticky relative">
              <p>posts widget</p>
              <p>categories</p>
            </div>
          </div>
        </div>
      </div>

    </>
  )
}


